### ISSUE TITLE
minor issue with WMI warnings

### ISSUE THREAD

**Issue by machineparadox** [geeklearningio/gl-vsts-tasks-azure#1]
Hi,

Not really an issue, but the ExecuteSQL task throws up a lot of warnings associated with import-module sqlps that can be avoided. There is an example of how to avoid it [here](https://developer42.wordpress.com/2016/02/03/powershell-sql-a-quick-fix-for-the-sqlps-problems/).

PS. Thanks for the tasks, I was doing this all in powershell, but this is much nicer.

Cheers

**Comment by sandorfr** [comment]
Hi, 

Thanks a lot for the tip, we will loon into it, but PRs are welcome. ☺

**Comment by asiffermann** [comment]
Thanks @machineparadox for the tip, it is now released in https://github.com/geeklearningio/gl-vsts-tasks-azure/releases/tag/1.2.0 on the Visual Studio MarketPlace!
