### ISSUE TITLE
It won't install in VSTS

### ISSUE THREAD

**Issue by petervandenhout** [geeklearningio/gl-vsts-tasks-azure#10]
When trying to install the tasks into VSTS it just gives the following error after a while.

`Extension operation denied by event callback. The HTTP request timed out after 00:01:40.`
`Version 1.3.1002`

Other task install fine, there seems to be an issue just with this one.

**Comment by asiffermann** [comment]
Hi @petervandenhout, and thank you for reporting this issue!

I'm currently investigating your issue...
In fact, I cannot install anymore our extension on a fresh VSTS account neither, it seems to be a regression with the last published version, or a change in the MarketPlace.

I am trying to publish a new version and see what is going on, I'll let you know when I'll find a resolution!

**Comment by asiffermann** [comment]
We can't figure why this is happening now...
I just reported the installation issue to Microsoft, I'll let you know when I'll get an answer!

Sorry for the inconvenience :(

**Comment by petervandenhout** [comment]
@asiffermann thanks for the quick response. I'll just wait a until the issue is resolved and try again then.

**Comment by asiffermann** [comment]
I just published a new version on the marketplace that I could install on a fresh VSTS account.
Do you mind letting me know if you can install it too?

Thank you!

**Comment by petervandenhout** [comment]
@asiffermann Yes it works. Many thanks, this will make my deployments so much easier :)

**Comment by asiffermann** [comment]
Glad to know it worked for you too!
Feel free to contact us if you encounter any issue or if you have a feature request :)

Happy deployments!
