### ISSUE TITLE
Swap Slot fails with "Error: Expectation Failed"

### ISSUE THREAD

**Issue by LarsKemmann** [geeklearningio/gl-vsts-tasks-azure#11]
I'm seeing this error more and more frequently -- this morning, I tried redeploying a release to Azure App Service five times in a row without success. (I'm still trying to get it to work.)

Any help would be appreciated, as this absolutely needs to run reliably for when we hand the continuous deployment pipeline over to our client.

The farthest I was able to get was a discussion on an MSDN forum somewhere talking about the slot swap process waiting for a 200 OK response from the source slot before it swaps it to the target. I haven't found any further information about that. Is there any way to bypass that, or at least get more details than just the "Expectation failed" error message? (What expectation is failing?)

> 2017-01-23T17:15:26.8104319Z ##[section]Starting: Swap Slot for Azure Web App: {SITE}
> 2017-01-23T17:15:26.8114320Z ==============================================================================
> 2017-01-23T17:15:26.8114320Z Task         : Azure App Service Manage (PREVIEW)
> 2017-01-23T17:15:26.8114320Z Description  : Start, Stop, Restart or Slot swap for an Azure App Service
> 2017-01-23T17:15:26.8114320Z Version      : 0.2.0
> 2017-01-23T17:15:26.8114320Z Author       : Microsoft Corporation
> 2017-01-23T17:15:26.8114320Z Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=831573)
> 2017-01-23T17:15:26.8114320Z ==============================================================================
> 2017-01-23T17:15:27.0894317Z 5d021b18-adb6-40b1-ac84-45b8b5115501 exists true
> 2017-01-23T17:15:27.2134320Z Requesting swap slot for Web App : {SITE}
> 2017-01-23T17:15:29.2360385Z Successfully updated deployment History at https://{SITE}-staging.scm.azurewebsites.net/deployments/931485191728282
> 2017-01-23T17:15:30.2281427Z Successfully updated deployment History at https://{SITE}.scm.azurewebsites.net/deployments/931485191728282
> 2017-01-23T17:15:30.2351542Z ##[error]Error: Failed to swap slots for Azure Web App: {SITE}. Error: Expectation Failed
> 2017-01-23T17:15:30.2371530Z ##[section]Finishing: Swap Slot for Azure Web App: {SITE}

**Comment by asiffermann** [comment]
Hi @LarsKemmann and thank you for submitting your issue! :)

I was first afraid of what was going on with our swap slot task, and then I realized in your log that you are using "Azure App Service Manage (PREVIEW)", which is the official task from Microsoft, still in preview.

Could you check if you are getting better results with our task?
You can easily see it in the "Deploy" category, with this icon:
![Icon](https://github.com/geeklearningio/gl-vsts-tasks-azure/raw/master/Tasks/SwapSlots/icon.png)

**Comment by LarsKemmann** [comment]
@asiffermann Thank you so much! I've switched to using your task and will try it out to see if reliability improves. It's an intermittent error, but we should know in a week if there's a significant improvement. :)

**Comment by asiffermann** [comment]
Great! I am keeping my fingers crossed for you!

As we are using our tasks intensively in several projects, I am pretty confident, but I would love to read your confirmation in a week :)

**Comment by LarsKemmann** [comment]
First result looks good. :) I think a key part may be the startup delay that's tolerated by your task vs. Microsoft's, but that's just a theory.

 > 2017-01-26T17:32:53.4498407Z ##[section]Starting: Swap Azure Web App slots: Staging to Production
 > 2017-01-26T17:32:53.4508406Z ==============================================================================
 > 2017-01-26T17:32:53.4508406Z Task         : Azure Web App Slots Swap
 > 2017-01-26T17:32:53.4508406Z Description  : Swap two deployment slots of an Azure Web App
 > 2017-01-26T17:32:53.4508406Z Version      : 1.3.1999
 > 2017-01-26T17:32:53.4508406Z Author       : Geek Learning
 > 2017-01-26T17:32:53.4508406Z Help         : [More Information](https://github.com/geeklearningio/gl-vsts-tasks-azure/wiki/Azure-Web-App-Slots-Swap) (Version 1.3.1999)
 > 2017-01-26T17:32:53.4508406Z ==============================================================================
 > 2017-01-26T17:32:54.7078422Z ##[command]Import-Module -Name C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager\AzureRM.Profile\AzureRM.Profile.psd1 -Global
 > 2017-01-26T17:32:55.0978667Z ##[command]Add-AzureRMAccount -ServicePrincipal -Tenant ******** -Credential System.Management.Automation.PSCredential
 > 2017-01-26T17:32:55.7484626Z ##[command]Select-AzureRMSubscription -SubscriptionId {SUBSCRIPTION} -TenantId ********
 > 2017-01-26T17:35:01.0280627Z Web App slot successfully swapped at Url : http://{SITE}-staging.azurewebsites.net
 > 2017-01-26T17:35:01.0494374Z ##[section]Finishing: Swap Azure Web App slots: Staging to Production

**Comment by asiffermann** [comment]
Hi @LarsKemmann!
Any update on this? Does our extension still helps you? :)

**Comment by LarsKemmann** [comment]
Sorry @asiffermann ! I thought I had replied via email on Thursday but it must not have gone through.

Success!! :)

I did see one instance of an “ExpectationFailed”-esque error but, unlike Microsoft’s preview task, yours actually provides the full error message:

 > 2017-02-02T19:23:02.9278410Z ##[section]Starting: Swap Azure Web App slots: Staging to Production
 > 2017-02-02T19:23:02.9298415Z
 > 
 > 2017-02-02T19:23:02.9298415Z Task         : Azure Web App Slots Swap
 > 2017-02-02T19:23:02.9298415Z Description  : Swap two deployment slots of an Azure Web App
 > 2017-02-02T19:23:02.9298415Z Version      : 1.3.1999
 > 2017-02-02T19:23:02.9298415Z Author       : Geek Learning
 > 2017-02-02T19:23:02.9298415Z Help         : [More Information](https://github.com/geeklearningio/gl-vsts-tasks-azure/wiki/Azure-Web-App-Slots-Swap) (Version 1.3.1999)
 > 2017-02-02T19:23:02.9298415Z
 > 
 > 2017-02-02T19:23:04.1598418Z ##[command]Import-Module -Name C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager\AzureRM.Profile\AzureRM.Profile.psd1 -Global
 > 2017-02-02T19:23:04.5088404Z ##[command]Add-AzureRMAccount -ServicePrincipal -Tenant ******** -Credential System.Management.Automation.PSCredential
 > 2017-02-02T19:23:05.1118417Z ##[command]Select-AzureRMSubscription -SubscriptionId {SUBSCRIPTION} -TenantId ********
 > 2017-02-02T19:23:06.8723203Z ##[error]The pipeline has been stopped.
 > 2017-02-02T19:23:06.8936317Z ##[error]{"Code":"ExpectationFailed","Message":"Cannot swap site slots for site '{SITE}-qa' because the 'Staging' slot did not respond to http ping.","Target":null,"Details":[{"Message":"Cannot swap site slots for site '{SITE}-qa' because the 'Staging' slot did not respond to http ping."},{"Code":"ExpectationFailed"},{"ErrorEntity":{"Code":"ExpectationFailed","Message":"Cannot swap site slots for site '{SITE}-qa' because the 'Staging' slot did not respond to http ping.","ExtendedCode":"04057","MessageTemplate":"Cannot swap site slots for site '{0}' because the '{1}' slot did not respond to http ping.","Parameters":[],"InnerErrors":[]}}],"Innererror":null}
 > 2017-02-02T19:23:06.9143192Z ##[section]Finishing: Swap Azure Web App slots: Staging to Production

Which is what I was guessing but is definitely more helpful than just having the code. :)

Thanks again!
~Lars

**Comment by asiffermann** [comment]
Great to know! :)
