### ISSUE TITLE
Feature Request: Traffic Manager endpoint enable/disable

### ISSUE THREAD

**Issue by martincostello** [geeklearningio/gl-vsts-tasks-azure#12]
In the scenario that the slot stop/start tasks are used while deploying an application update, if the slot is pointed to by a Traffic Manager rule, without manual intervention it could still be possible for users to be directed to a stopped slot if the update happens quickly enough for the Traffic Manager up/down detection to do this automatically.

If tasks were available to disable and enable an endpoint from a Traffic Manager rule, then a task chain such as the below could be used to keep user-facing application uptime as high as possible:

  1. Disable _Website A_ in Traffic Manager profile _T_.
  1. Stop _Website A_.
  1. Update _Website A_ version _x_ to version _x+1_.
  1. Start _Website A_.
  1. Enable _Website A_ in Traffic Manager profile _T_.
  1. Disable _Website B_ in Traffic Manager profile _T_.
  1. Stop _Website B_.
  1. Update _Website B_ version _x_ to version _x+1_.
  1. Start _Website B_.
  1. Enable _Website B_ in Traffic Manager profile _T_.

**Comment by asiffermann** [comment]
Hi @martincostello and thank you for your Feature Request! :)

I do not use Traffic Manager myself, so I have a few questions about your use case:

1. Why couldn't you deploy to a specific deployment slot, then swap it with the one pointed to by your Traffic Manager rule? The task chain would be:
    1. Stop "Website A - Staging Slot"
    2. Update "Website A - Staging Slot" version x to version x+1.
    3. Start "Website A - Staging Slot"
    4. Swap "Website A - Staging Slot" with "Website A - Main Slot"

2. You are talking about disable and enable an endpoint. So you might refer to the PowerShell commands `Enable-AzureRmTrafficManagerEndpoint` and `Disable-AzureRmTrafficManagerEndpoint`, am I right?

3. If I found out the correct commands, the following should be the mandatory parameters exposed by the new tasks. Would you see another optional parameters?
    1. Azure RM Subscription
    2. Resource Group Name
    3. Profile Name
    4. Endpoint Name

Thank you!

**Comment by martincostello** [comment]
@asiffermann Thanks for looking into this. To answer your questions:

  1. I don't use slot swapping as my slots would need "sticky" configuration settings so they keep working correctly (so keys for staging don't move to production, for example), which would then cause the AppPool to restart and would lead to the same "downtime" problem.
  1. Yes, those appear to be the correct two PowerShell cmdlets.
  1. Looking at the documentation, you also need to expose the ability to set the ```-Type``` parameter (vaid values ```ExternalEndpoints``` and ```NestedEndpoints```), although it sounds weird that that should be necessary as that sounds like something that should only be needed for an new endpoint.

**Comment by asiffermann** [comment]
Thank you for your answers!

I honestly do not know when I will have time to implement it, but according to your use case, I think we should definitely include it in our extension.

That being said, if it is an urgent need for you, and if you have a little time for it (or someone else!), we would be happy to accept a PR :)

**Comment by luigiw** [comment]
+1 on this

Our use case is that 2 apps behind the traffic manager are in 2 different Azure locations for disaster recovery purpose. I don't think deployment slot is good enough for our case.

When it comes to deployment, I would like to shut down traffic to one location while deployment is ongoing. This way I can make sure on 2 versions of the App is running behind traffic manager at the same time.
