### ISSUE TITLE
Swap slots randomly fails

### ISSUE THREAD

**Issue by pb123456** [geeklearningio/gl-vsts-tasks-azure#14]
I have four tasks for publishing a web app/app service:

1. Stop Azure App Service, slot staging
2. Deploy Azure App Service to Slot, slot staging
3. Start Azure App Service, slot staging
4. Swap Slots (log reports version 0.2.4), source slot staging and swap with production checked

Swapping tends to fail. If swapping goes fine I get these lines in the log:

Requesting swap slot for Web App : <my app>
Successfully swapped web app <my app> slots from staging to production

When swapping fails, the second line is removed and error is reported:

##[error]Error: Failed to swap slots for Azure Web App: <my app>. Error: Bad Request

Swapping slots manually in Azure goes fine.

**Comment by asiffermann** [comment]
Hi @pb123456 and thank you for submitting your issue! 😃

The [current version of our extension](https://marketplace.visualstudio.com/items?itemName=geeklearningio.gl-vsts-tasks-azure) deployed to the marketplace is 1.3.1999, so I am wondering why you are seeing such a version in your logs.

Before investigating further, could you please attach your full build log to your issue (more, it would be helpful if you could add or set the `System.Debug` variable to `true` on your Build Definition)?

Thank you!

**Comment by pb123456** [comment]
Hi!

Thanks for the feedback! It pointed me in the right direction, which was that I didn't use your extensions at all... I used a Microsoft extension, their link led to a 404, I then search and found a link to you extension on a MS page, and as it looked similar I just assumed that I was on the correct site. At least I'm using your extension now - and swapping went just fine in my first try.

**Comment by asiffermann** [comment]
Great to know! 😃 Thank you!
