### ISSUE TITLE
Required does not make sense for boolean

### ISSUE THREAD

**Issue by chrisrpatterson** [geeklearningio/gl-vsts-tasks-azure#16]
I noticed this issue when looking through various tasks in the marketplace and seeing how they interacted with the new editor.  You have a Boolean checkbox property that is marked as required https://github.com/geeklearningio/gl-vsts-tasks-azure/blob/master/Tasks/AzCopy/task.json#L155 which seems a bit counter intuitive as false is the default state.  

We are working on a hotfix for the editor that will make this work out so that we will essentially ignore the required flag for Boolean properties but it would be good to change that in your task as well.

Also the more information link in your task points at this url https://github.com/geeklearningio/gl-vsts-tasks-files/wiki which seems like the wrong place.

**Comment by sandorfr** [comment]
Thanks for the PR, the update has been published to the marketplace.

**Comment by chrisrpatterson** [comment]
No Problem

Sent from Nine<http://www.9folders.com/>
________________________________
