### ISSUE TITLE
 "HostAuthorizationNotFoundException" error when trying to install to VSTS

### ISSUE THREAD

**Issue by sim1986** [geeklearningio/gl-vsts-tasks-azure#18]
After clicking install, selecting my target VSTS account and selecting confirm I get the following error:

HostAuthorizationNotFoundException

**Comment by asiffermann** [comment]
Hi @sim1986, and thank you for reporting this issue!

As I told you before, I cannot reproduce your installation error on a fresh VSTS account, so could you try the following:

- Can you install another extension to the same account? (you can try our [File Patch extension](https://marketplace.visualstudio.com/items?itemName=geeklearningio.gl-vsts-tasks-file-patch) for instance, or one from any other publisher)
- Could you open your browser's developer tools when you try to install the extension and report us any error you might see in it (console or network).
- Could you provide some screenshots of your failed installation so I could eventually contact directly Microsoft and the Marketplace team to see if they can help us for your error

Thank you, and sorry again for the inconvenience!

**Comment by sim1986** [comment]
Hi, I tried another extension and could not install with a different error. I have logged on to VSTS with a different machine and the install worked. Thanks

**Comment by asiffermann** [comment]
Great to know! Feel free to ask any further question about our extensions if needed 😃
