### ISSUE TITLE
Deprecate Start/Stop/Swap

### ISSUE THREAD

**Issue by sandorfr** [geeklearningio/gl-vsts-tasks-azure#19]
We should consider deprecating those tasks since the official ones are out.

**Comment by sandorfr** [comment]
Actually it might be worth keeping them but adding missing features in the official ones like stopping web jobs.

**Comment by asiffermann** [comment]
The official “Azure App Service Manage” task from Microsoft can now do whatever we always did with our tasks. Next release will deprecate those tasks.
Farewell to them! 😢😘
