### ISSUE TITLE
Resource Group Names

### ISSUE THREAD

**Issue by james5101** [geeklearningio/gl-vsts-tasks-azure#23]
Hello, 

Is it possible to integrate Resource Group Name as a parameter in determining which web app to stop? We ran into an issue deploying new web apps (in internal ASE) which will allow you to have duplicate web app names (trying to deploy side by side and then cut over). Since Get-ResourceGroupName returned an array our VSTS release would fail, not knowing which web app to stop.

**Comment by sandorfr** [comment]
This is definitely something we could do.

That said, I think the new built in official task has this option. Have you had a look?

**Comment by asiffermann** [comment]
Our "Azure Web App Stop" task is now deprecated as referred in #19.
The official “Azure App Service Manage” task from Microsoft should be used instead, and can target a specific Resource Group.
