### ISSUE TITLE
Mime Types getting reset to "application/octet-stream"

### ISSUE THREAD

**Issue by jebbisson** [geeklearningio/gl-vsts-tasks-azure#26]
When copying from my git source and into my blob store the mime types get replaced with "application/octet-stream" which is causing some issues.
With the Microsoft version of this task I am able to set "/SetContentType" and it would copy over all the mime types.

Is there any way to do that with this task?

I like this task better but right now I can't use it.
Thanks.

**Comment by sandorfr** [comment]
Which task are you talking about ? Azcopy?

**Comment by jebbisson** [comment]
Yes, azcopy is what I am referring to.

**Comment by sandorfr** [comment]
I'm in the process of adding an Additional Argument field. Unfortunately, Microsoft seems to have introduced breaking changes on the Arm client and authentication which are slowing me down.

**Comment by sandorfr** [comment]
The update has been pushed ;)
