### ISSUE TITLE
HelperFunctions.ps1 - function Get-ResourceGroupName returns empty string

### ISSUE THREAD

**Issue by miicahjardine** [geeklearningio/gl-vsts-tasks-azure#39]
When running this task on Azure Devops  on a private agent with the latest version 14.1.1999 the helper method Get-ResourceGroupName returns an empty string.

The problem appears to be that in older PS modules Get-AzureRMResource returns a object with a value for 'ResourceName'.  In new PS modules the get-azureRMResource returns an object with a value for 'Name'.  This means that line 21 returns nothing.  

If Line 21 can be updated to...

$resourceDetails = (Get-AzureRMResource -ErrorAction Stop) | Where-Object { ($_.ResourceName -eq $resourceName -or $_.Name -eq $resourceName) -and $_.ResourceType -eq $resourceType } -Verbose

it would mean that this helper would work with newer versions of the PS modules.

Cheers

**Comment by sandorfr** [comment]
The update has been published.
