### ISSUE TITLE
Azure Resource not found.

### ISSUE THREAD

**Issue by bartek-stopa** [geeklearningio/gl-vsts-tasks-azure#43]
Since 26.08.2019 it looks as if some of your task stop working. The error message is: Azure Resource not found. It appears e.g. on Azure SQL Execute Query, Azure Web App Start, Azure Web App Stop etc.

**Comment by IoBebe** [comment]
i have the same issue.
here's some extra logs

![issue-runAzureSql](https://user-images.githubusercontent.com/8350561/66016220-60d5ae80-e4de-11e9-8bbf-0ce219dbbeb7.PNG)

**Comment by IoBebe** [comment]
seems similar with #39, or rather #39 highlights the root cause

**Comment by sandorfr** [comment]
I published the update.
